const content =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras gravida, orci nec feugiat commodo, ipsum orci consequat nulla.";

const categoryBrands = [
        {
            id: 1,
            name: "Sony",
            image: require("./assets/sonylogos.png"), 
            },
            {
            id: 2,
            name: "Canon",
            image: require("./assets/canonlogos.png"),
            },
            {
            id: 3,
            name: "Fujifilm",
            image: require("./assets/fujilogos.png"),
            },
            {
            id: 4,
            name: "Lumix",
            image: require("./assets/lumixlogos.png"),
            },
            {
            id: 5,
            name: "Sigma",
            image: require("./assets/sigmalogos.png"),
            },
            {
            id: 6,
            name: "Tamron",
            image: require("./assets/tamronlogos.png"),
            },
        ];

const datas = [
    {
        id: 1,
        category_id: 1,
        name: "Sony A5100 & 16-50mm f/3.5-5.6 OSS",
        price_6h: 50000,
        price_12h: 75000,
        price_24h: 150000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA5100.webp"),
        content : content,
    },
    {
        id: 2,
        category_id: 1,
        name: "Sony A6000 & 16-50mm f/3.5-5.6 OSS",
        price_6h: 60000,
        price_12h: 85000,
        price_24h: 175000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6000.webp"),
        content : content,
    },
    {
        id: 3,
        category_id: 1,
        name: "Sony A6300",
        price_6h: 65000,
        price_12h: 100000,
        price_24h: 200000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6300.webp"),
        content : content,
    },
    {
        id: 4,
        category_id: 1,
        name: "Sony A6100",
        price_6h: 70000,
        price_12h: 110000,
        price_24h: 225000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6100.webp"),
        content : content,
    },
    {
        id: 5,
        category_id: 1,
        name: "Sony A6400",
        price_6h: 750000,
        price_12h: 125000,
        price_24h: 250000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6400.webp"),
        content : content,
    },
    {
        id: 6,
        category_id: 1,
        name: "Sony A6500",
        price_6h: 75000,
        price_12h: 125000,
        price_24h: 250000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6500.webp"),
        content : content,
    },
    {
        id: 7,
        category_id: 1,
        name: "Sony A6600",
        price_6h: 80000,
        price_12h: 150000,
        price_24h: 275000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6600.webp"),
        content : content,
    },
    {
        id: 8,
        category_id: 1,
        name: "Sony A6700",
        price_6h: 80000,
        price_12h: 150000,
        price_24h: 275000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA6700.webp"),
        content : content,
    },
    {
        id: 9,
        category_id: 1,
        name: "Sony A7 Mark II",
        price_6h: 100000,
        price_12h: 125000,
        price_24h: 250000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7ii.webp"),
        content : content,
    },
    {
        id: 10,
        category_id: 1,
        name: "Sony A7 Mark III",
        price_6h: 125000,
        price_12h: 175000,
        price_24h: 350000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7iii.webp"),
        content : content,
    },
    {
        id: 11,
        category_id: 1,
        name: "Sony A7 Mark IV",
        price_6h: 200000,
        price_12h: 250000,
        price_24h: 450000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7iv.webp"),
        content : content,
    },
    {
        id: 12,
        category_id: 1,
        name: "Sony A7R Mark III",
        price_6h: 125000,
        price_12h: 175000,
        price_24h: 375000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7Riii.webp"),
        content : content,
    },
    {
        id: 13,
        category_id: 1,
        name: "Sony A7R Mark IV",
        price_6h: 200000,
        price_12h: 225000,
        price_24h: 475000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7Riv.webp"),
        content : content,
    },
    {
        id: 14,
        category_id: 1,
        name: "Sony A7S",
        price_6h: 100000,
        price_12h: 150000,
        price_24h: 250000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7S.webp"),
        content : content,
    },
    {
        id: 15,
        category_id: 1,
        name: "Sony A7S Mark II",
        price_6h: 125000,
        price_12h: 175000,
        price_24h: 350000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7Sii.webp"),
        content : content,
    },
    {
        id: 16,
        category_id: 1,
        name: "Sony A7S Mark III",
        price_6h: 350000,
        price_12h: 500000,
        price_24h: 650000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7Siii.webp"),
        content : content,
    },
    {
        id: 17,
        category_id: 1,
        name: "Sony A7C",
        price_6h: 125000,
        price_12h: 175000,
        price_24h: 350000,
        brand: "Sony",
        category_name: "SONY",
        image : require("./assets/SonyA7C.webp"),
        content : content,
    },
    {
        id: 18,
        category_id: 2,
        name: "Canon EOS M50 & 15-45mm f/3.5-6.3 IS STM",
        price_6h: 60000,
        price_12h: 90000,
        price_24h: 170000,
        brand: "Canon",
        category_name: "CANON",
        image: require("./assets/CanonM50.webp"),
        content: content,
    },
    {
        id: 19,
        category_id: 2,
        name: "Canon EOS 90D & 18-55mm f/3.5-5.6 IS STM",
        price_6h: 80000,
        price_12h: 120000,
        price_24h: 230000,
        brand: "Canon",
        category_name: "CANON",
        image: require("./assets/CanonEOS90D.webp"),
        content: content,
    },
    {
        id: 20,
        category_id: 2,
        name: "Canon EOS 5D Mark IV",
        price_6h: 150000,
        price_12h: 200000,
        price_24h: 400000,
        brand: "Canon",
        category_name: "CANON",
        image: require("./assets/Canon5DMarkIV.webp"),
        content: content,
    },
    {
        id: 21,
        category_id: 2,
        name: "Canon EOS R5",
        price_6h: 250000,
        price_12h: 350000,
        price_24h: 700000,
        brand: "Canon",
        category_name: "CANON",
        image: require("./assets/CanonEOSR5.webp"),
        content: content,
    },
    {
        id: 22,
        category_id: 2, 
        name: "Canon EOS 1D X Mark III",
        price_6h: 350000,
        price_12h: 500000,
        price_24h: 800000,
        brand: "Canon",
        category_name: "CANON",
        image: require("./assets/Canon1DXMarkIII.webp"),
        content: content,
    },
];

const featured = [
    {
        id: 1,
        category_id: 1,
        name : "Travelling" ,
        description : "Kamera lensa foto, flash & continuous lighting support, studio equipment, background, modifier dan lainnya ada disini",
        image : require("./assets/CanonM50.webp"),
        content : content,
    },
    {
        id: 2,
        category_id: 2,
        name: "Multimedia" ,
        description : " flash & continuous lighting support, studio equipment, background, modifier dan lainnya ada disini",
        image : require ("./assets/SonyA6700.webp"),
        content : content,
    },
    {
        id: 3,
        category_id: 3,
        name: "Photographer" ,
        description : "Kamera lensa foto, flash & continuous lighting support, studio equipment, background, modifier dan lainnya ada disini",
        image : require("./assets/SonyA6400.webp"),
        content : content,
    },
    {
        id: 4,
        category_id: 4,
        name: "CINEMA",
        description: "Kamera lensa sinema, video support, monitor, follow focus, stabilizer, tripod dan lainnya ada disini",
        image : require("./assets/SonyA5100.webp"),
        content : content,
    }
];

export const getBrandInfo = (categoryId) => {
    const brand = categoryBrands.find(item => item.id === categoryId);
    return brand || {};
};  

export {datas, categoryBrands, featured};